// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using REManager.DataAccess;
using System;

namespace REManager.Migrations
{
    [DbContext(typeof(REPropertyDbContext))]
    [Migration("20180421191051_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("REManager.Models.REProperty", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<bool>("IsForRent");

                    b.Property<bool>("IsForSale");

                    b.Property<string>("Name");

                    b.Property<string>("PostalCode");

                    b.Property<int?>("PurchaseAmount");

                    b.Property<DateTime>("PurchaseDate");

                    b.Property<string>("State");

                    b.Property<string>("Unit");

                    b.HasKey("Id");

                    b.ToTable("ReProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
